### ISSUE TITLE
Empty theme names on VSCodeThemes

### ISSUE THREAD

**Issue by jschr** [konradkeska/outerspace-next#1]
Hey! First off, nice theme :) 

Your theme is currently trending on vscodethemes.com and I noticed there are a few themes that don't have a name: https://vscodethemes.com/e/konradkeska.outerspace-next 

As far as I can tell, these are old themes that need to be removed. This is currently a manual process on my end. 

Before I do, could you confirm if the themes with an empty name should be deleted? 

Thanks!

**Comment by konradkeska** [comment]
Hey, 

Thanks for taking your time to point this out and also sorry for my late response, I was pretty busy at work lately. I've deleted the test theme with an empty name from repository.

Have a nice day!
